import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const y = new Date();

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        My<a href="javascript:void(0)"> Portfolio</a>
      </h1>

      <p className={styles.description}>Let me introduce myself</p>

      <a href="javascript:void(0)" className={styles.card}>
        <h2>Personal information &rarr;</h2>
        <p>Name: Athiwat Harnpimy</p>
        <p>Gender: Male</p>
        <p>Age: {y.getFullYear() - 1992}</p>
        <p>Email: athiwat.8971@gmail.com</p>
        <p>Career: Developer</p>
        <p>Country: Thailand</p>
        <p>Interest: IT,GEEK,Coding,Play Guitar and Play Games</p>
      </a>

      <footer className={styles.footer}>Powered by aof </footer>
    </div>
  );
}
